// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs73Vkn5an5PZTL-jZ3kAfoKFnqwHzPH0',
    appId: '1:989936298324:web:4e98b74badd02908ec80c1',
    messagingSenderId: '989936298324',
    projectId: 'kothopokothon-e7bca',
    authDomain: 'kothopokothon-e7bca.firebaseapp.com',
    storageBucket: 'kothopokothon-e7bca.firebasestorage.app',
    measurementId: 'G-7P7T8TC3D8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9vK5sE2688rqLZNavY9GZ0rWqUIbVXGY',
    appId: '1:989936298324:android:e879e9440e817e9aec80c1',
    messagingSenderId: '989936298324',
    projectId: 'kothopokothon-e7bca',
    storageBucket: 'kothopokothon-e7bca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfAulJzp6PnpFrz5Q-3zGGNe3t8MUcAoc',
    appId: '1:989936298324:ios:138c5333b2e1ef72ec80c1',
    messagingSenderId: '989936298324',
    projectId: 'kothopokothon-e7bca',
    storageBucket: 'kothopokothon-e7bca.firebasestorage.app',
    iosBundleId: 'com.cse21.kothopokothon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs73Vkn5an5PZTL-jZ3kAfoKFnqwHzPH0',
    appId: '1:989936298324:web:cb1d04fcae71afa4ec80c1',
    messagingSenderId: '989936298324',
    projectId: 'kothopokothon-e7bca',
    authDomain: 'kothopokothon-e7bca.firebaseapp.com',
    storageBucket: 'kothopokothon-e7bca.firebasestorage.app',
    measurementId: 'G-73K7WNP9ZR',
  );
}
